services:
  - type: web
    name: portfolio-django
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: False